/**
 * "FIX THIS WITH ZENO" MUST NEVER BE A DEAD END.
 *
 * Found in staging acceptance, on a real login: the action dispatched an event
 * that only the floating launcher listened for, and the launcher renders
 * nothing when its workspace or AI-suite gate is unresolved. So the click did
 * precisely nothing, silently — the worst possible outcome for the one button
 * that carries the product's central promise.
 *
 * Certified here in a real DOM, because the bug lived in the interaction
 * between a dispatcher and a listener that may or may not be rendered, which
 * source inspection cannot settle.
 */
// A minimal window rather than a DOM library: askZeno only needs event
// dispatch and a settable location, and adding a dependency to test six lines
// would be the wrong trade. Node supplies EventTarget and CustomEvent.
let navigatedTo: string | null = null;
const target = new EventTarget();
const fakeWindow = {
  addEventListener: target.addEventListener.bind(target),
  removeEventListener: target.removeEventListener.bind(target),
  dispatchEvent: target.dispatchEvent.bind(target),
  location: { get href() { return "https://example.test/intelligence"; }, set href(v: string) { navigatedTo = v; } },
};
(globalThis as unknown as Record<string, unknown>).window = fakeWindow;
const dom = { window: fakeWindow };

const { askZeno, ASK_ZENO_EVENT, ZENO_PAGE_PATH } = await import("../src/lib/divinex/ask-zeno.ts");

let bad = 0;
const check = (l: string, ok: boolean, n = "") => { console.log(`${ok ? "PASS" : "FAIL"} ${l}${n ? ` — ${n}` : ""}`); if (!ok) bad++; };

const RECOMMENDATION =
  "Ascend found this on my site (Conversion Journey), low impact:\n\n\"TODAY (under 2 hours): Add a guarantee statement to the /programs/ page hero section.\"";

// ── No launcher rendered (the staging case) ────────────────────────────────
navigatedTo = null;
askZeno({ prompt: RECOMMENDATION });
check("with no launcher, the click still goes somewhere", navigatedTo !== null);
check("...to the Ask Zeno page the sidebar already uses",
  (navigatedTo ?? "").startsWith(`${ZENO_PAGE_PATH}?ask=`), navigatedTo ?? "(nowhere)");
const carried = decodeURIComponent((navigatedTo ?? "").split("?ask=")[1] ?? "");
check("...carrying the recommendation itself, not a summary",
  carried.includes("Add a guarantee statement") && carried.includes("Conversion Journey"), carried.slice(0, 70));

// ── A launcher that CANNOT open must not swallow the request ───────────────
navigatedTo = null;
const silent = () => { /* registered, but never acknowledges */ };
dom.window.addEventListener(ASK_ZENO_EVENT, silent);
askZeno({ prompt: RECOMMENDATION });
check("a listener that cannot open does not suppress the fallback", navigatedTo !== null);
dom.window.removeEventListener(ASK_ZENO_EVENT, silent);

// ── A launcher that CAN open handles it, with no navigation ────────────────
navigatedTo = null;
let seen: string | null = null;
const opener = (e: Event) => {
  const d = (e as CustomEvent<{ prompt: string; handled?: boolean }>).detail;
  d.handled = true;      // exactly what ZenoLauncher does when it can render
  seen = d.prompt;
};
dom.window.addEventListener(ASK_ZENO_EVENT, opener);
askZeno({ prompt: RECOMMENDATION });
check("when the panel can open, it receives the request", seen === RECOMMENDATION);
check("...and the customer is NOT navigated away from the page they were on",
  navigatedTo === null, navigatedTo ?? "");
dom.window.removeEventListener(ASK_ZENO_EVENT, opener);

// ── The handoff must survive a long recommendation ─────────────────────────
navigatedTo = null;
const long = "x".repeat(5000);
askZeno({ prompt: long });
check("a very long recommendation still produces a usable URL",
  navigatedTo !== null && navigatedTo!.length < 2000, `${navigatedTo?.length ?? 0} chars`);

// ── Nothing is generated by handing off ────────────────────────────────────
check("the fallback only opens a page; it never sends or generates",
  (navigatedTo ?? "").includes("?ask=") && !(navigatedTo ?? "").includes("send") && !(navigatedTo ?? "").includes("confirm"));

console.log(bad === 0 ? "\nALL PASS" : `\n${bad} FAILED`);
process.exit(bad === 0 ? 0 : 1);
