import Link from "next/link";
import { resolveCustomBrand } from "@/lib/landing/resolve-brand";

export const metadata = {
  title: "Responsible AI Policy",
  description:
    "How Flow's AI features work, their limitations, and the human oversight built into the product.",
};

export default async function ResponsibleAiPage() {
  const brand = await resolveCustomBrand();
  const supportMailto = `mailto:${brand.supportEmail}`;

  return (
    <div className="mx-auto max-w-3xl px-4 py-16">
      <Link
        href="/"
        className="text-sm text-muted-foreground hover:text-primary"
      >
        &larr; Back to home
      </Link>

      <article className="prose dark:prose-invert mt-8 max-w-none">
        <h1>Responsible AI Policy</h1>
        <p className="text-sm text-muted-foreground">
          Last updated: July 26, 2026
        </p>
        <p>
          {brand.name}, provided by Jade&rsquo;s Gems &amp; SOULutions LLC,
          doing business as DivineX, includes optional AI-powered features.
          This page explains what they are, how they work, and their
          limitations &mdash; in plain language, matched to what&rsquo;s
          actually built today. This policy is governed by the laws of the
          State of Texas, United States, on the same terms as Section 14 of
          our <Link href="/terms">Terms of Service</Link>.
        </p>

        <h2>1. What {brand.name}&rsquo;s AI features do</h2>
        <p>
          All of {brand.name}&rsquo;s AI features share one persona per
          workspace (a system prompt you write, plus optional business
          hours, escalation rules, and a knowledge base drawn from your own
          website) &mdash; the same identity answers across whichever
          channels you enable:
        </p>
        <ul>
          <li>
            <strong>In-app AI Assistant</strong> &mdash; answers questions
            and, for actions that change data (like creating a contact or
            sending a message), asks you to confirm before it acts.
          </li>
          <li>
            <strong>Web Chat</strong> &mdash; an AI agent embedded on your
            website that can answer visitor questions and capture lead
            details.
          </li>
          <li>
            <strong>SMS, WhatsApp, and Voice (inbound)</strong> &mdash; the
            same persona auto-replies to incoming messages and can answer
            inbound phone calls.
          </li>
          <li>
            <strong>Outbound Voice</strong> (opt-in, separately enabled)
            &mdash; the AI can proactively call your contacts, either one at
            a time or as part of a campaign you configure.
          </li>
        </ul>

        <h2>2. How these features work, technically</h2>
        <p>
          Text-based AI replies (assistant, web chat, SMS, WhatsApp) are
          generated by sending the conversation and your configured persona
          to OpenRouter, a third-party AI model gateway, which routes the
          request to an underlying language model (Claude by default; you
          or we may configure a different model). Voice calls are
          additionally handled by Vapi, a third-party voice AI provider,
          which converts speech to text, generates a response, and converts
          it back to speech in real time.
        </p>

        <h2>3. Human oversight built into the product</h2>
        <p>
          Some AI actions require your explicit confirmation before they
          take effect, rather than executing automatically &mdash; this is
          a deliberate design choice for actions with real-world
          consequences (for example, creating records or sending messages
          on your behalf in certain flows). Outbound voice calling
          additionally passes through a compliance gate that checks
          consent, calling windows, and contact frequency before any call is
          placed &mdash; you remain responsible for your own compliance
          obligations (Section 5 of our{" "}
          <Link href="/terms">Terms of Service</Link>) on top of this
          safeguard.
        </p>

        <h2>4. Limitations</h2>
        <p>
          AI-generated content can be wrong. It may misunderstand context,
          generate inaccurate information, or produce a response that
          doesn&rsquo;t match your intent &mdash; especially for nuanced,
          sensitive, or high-stakes conversations. You are responsible for:
        </p>
        <ul>
          <li>Reviewing your persona configuration before enabling a channel;</li>
          <li>
            Monitoring AI conversations ({brand.name} provides transcripts
            and session logs for this purpose);
          </li>
          <li>
            Not relying on AI output for legal, medical, financial, or other
            advice requiring professional judgment;
          </li>
          <li>
            Disclosing AI use to the people you contact where law or a
            connected platform&rsquo;s policy (for example, WhatsApp)
            requires it.
          </li>
        </ul>

        <h2>5. Data use by our AI providers</h2>
        <p>
          Conversation content you send through {brand.name}&rsquo;s AI
          features is transmitted to OpenRouter (text) and/or Vapi (voice)
          to generate responses, and is stored in our own database as
          described in our <Link href="/privacy">Privacy Policy</Link>.
          Text and voice are handled differently by these providers, based
          on each provider&rsquo;s own published policy:
        </p>
        <p>
          <strong>Text (OpenRouter).</strong> OpenRouter&rsquo;s documented
          default is that it does not store submitted prompts or
          completions, and does not use them to train or improve models,
          unless data collection is explicitly enabled at the account
          level. Our integration does not enable that data collection, so
          text conversations fall under OpenRouter&rsquo;s default (no
          storage, no training use) as a matter of configuration.
        </p>
        <p>
          <strong>Voice (Vapi).</strong> Vapi&rsquo;s published privacy
          policy states that call recordings, transcripts, and logs may be
          retained and used to help improve their AI services, unless a
          privacy-enhanced configuration is enabled for the account. We are
          evaluating enabling that configuration; until we do, voice call
          content may be used by Vapi consistent with their standard policy.
        </p>

        <h2>6. Model changes</h2>
        <p>
          The specific AI model or provider we use may change over time as
          we adopt better or more cost-effective options. Material changes
          to which provider(s) process your data will be reflected in this
          policy and our <Link href="/privacy">Privacy Policy</Link>.
        </p>

        <h2>7. Related Documents</h2>
        <p>
          This policy should be read together with our{" "}
          <Link href="/terms">Terms of Service</Link> (Section 6) and{" "}
          <Link href="/privacy">Privacy Policy</Link>.
        </p>

        <h2>8. Contact</h2>
        <p>
          Questions about how {brand.name}&rsquo;s AI features work &mdash;{" "}
          <a
            href={supportMailto}
            className="underline-offset-4 hover:underline"
          >
            email {brand.supportEmail}
          </a>
          , or write to us at:
        </p>
        <p>
          Jade&rsquo;s Gems &amp; SOULutions LLC
          <br />
          440 Louisiana St
          <br />
          Houston, TX 77002
          <br />
          United States
        </p>
      </article>
    </div>
  );
}
